### ISSUE TITLE
Thanks for dito update, but live not working today.

### ISSUE THREAD

**Issue by ykhehra1** [YoColdRain/Ditto-Rain#2]
Thanks for dito update, but live not working today. Site was down for hours today, looks like they change something again.

log:

15:08:07 T:16744  NOTICE: DVDPlayer: Opening: |referer=http://www.dittotv.com/index.php?r=live-tv/view&id=10201
15:08:07 T:16744 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:08:07 T:7908  NOTICE: Thread DVDPlayer start, auto delete: false
15:08:07 T:7908  NOTICE: Creating InputStream
15:08:07 T:7908 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(|referer=http) in |referer=http://www.dittotv.com/index.php?r=live-tv/view&id=10201
15:08:07 T:7908   ERROR: CDVDPlayer::OpenInputStream - error opening [|Referer=http://www.dittotv.com/index.php?r=live-tv/view&id=10201]
15:08:07 T:7908  NOTICE: CDVDPlayer::OnExit()
15:08:07 T:16744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ditto-rain/?mode=28&name=India+Today&url=http%3A%2F%2Fwww.dittotv.com%2Findex.php%3Fr%3Dlive-tv%2Fview%26id%3D10201&image=http%3A%2F%2F77.36.61.42%2Fimages_ditto%2Fnew_images%2Flivetv%2F10201.jpg]

**Comment by YoColdRain** [comment]
yes, thats because they updated the code.  Please do not use this repo for issues, visit addon thread on official Kodi forums to stay updated.
